name: funpro
version: 0.1.0.0
github: "githubuser/funpro"
license: BSD-3-Clause
author: "Author name here"
maintainer: "example@example.com"
copyright: "2024 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/funpro#readme>

dependencies:
  - base >= 4.7 && < 5
  - scotty >= 0.22
  - mongoDB >= 2.7.1.4
  - aeson >= 2.1.2.1
  - random >= 1.2
  - mtl
  - containers
  - text
  - bson

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

default-extensions:
  - OverloadedStrings

executables:
  funpro:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - funpro
      - scotty
      - mongoDB
      - random
      - mtl
      - containers
      - text
      - bson

tests:
  funpro-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - funpro
      - scotty
      - mongoDB
      - random
      - mtl
      - containers
      - text
      - bson